### ISSUE TITLE
IPToS too long

### ISSUE THREAD

**Issue by jccrespo** [jhthorsen/app-docsisious#2]
It always shows this error messages with any extended value

0x4040ff
0x3030ff

**Comment by jhthorsen** [comment]
Thanks for reporting in 👍 

Could you please provide me with a sample data structure? I don't know how to reproduces this with the data you have provided. Also, do you have a binary file with the expected result?

It's very important that the sample data you provide is to the point. It's very hard to figure this out if you provide a huge sample file.

**Comment by jccrespo** [comment]
First, thank you, really it help a lot of people like me and Its such an honor meet you

Please see the file attached

Have a Greaaat Day!

Juan C. Crespo R.
Cuando la ignorancia se impone
la raz??n cordialmente cede paso ;)

**Comment by jhthorsen** [comment]
Sorry, I cannot see any files attached. Can you send it to jhthorsen@cpan.org ?

**Comment by jccrespo** [comment]
sent from jcrespo@ifx.com.ve


Juan C. Crespo R.
Cuando la ignorancia se impone
la raz??n cordialmente cede paso ;)


________________________________

**Comment by jhthorsen** [comment]
I've looked at the same file now, and I'm not sure what you expect it to show. `0x3030ff` isn't an error message, it's a hexadecimal value.

**Comment by jccrespo** [comment]
Yes, but your docsis writer takes that value as an error.


How to test it?

1.- Upload the file to your website

2.- try to download


Thanks for your time


Juan C. Crespo R.
Cuando la ignorancia se impone
la raz??n cordialmente cede paso ;)


________________________________

**Comment by jhthorsen** [comment]
Thank you! I just fixed it in https://github.com/jhthorsen/docsis-configfile/commit/8e82729ae8770a355a7d3b85aca72a79acdcca4f

I've reloaded the webservice, so you should be able to get the expected result.

**Comment by jccrespo** [comment]
No, thanks to you Sir, thanks for your time, it helps a lot


Juan C. Crespo R.
Cuando la ignorancia se impone
la raz??n cordialmente cede paso ;)


________________________________
